# Form implementation generated from reading ui file 'dk_khoahoc.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt6.QtWidgets import QMessageBox, QTableWidgetItem

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 100, 20))
        self.label.setObjectName("label")
        self.txt_ten = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_ten.setGeometry(QtCore.QRect(100, 20, 200, 25))
        self.txt_ten.setObjectName("txt_ten")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 100, 20))
        self.label_2.setObjectName("label_2")
        self.txt_email = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_email.setGeometry(QtCore.QRect(100, 60, 200, 25))
        self.txt_email.setObjectName("txt_email")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 100, 20))
        self.label_3.setObjectName("label_3")
        self.cb_khoahoc = QtWidgets.QComboBox(parent=Dialog)
        self.cb_khoahoc.setGeometry(QtCore.QRect(100, 100, 200, 25))
        self.cb_khoahoc.setObjectName("cb_khoahoc")
        self.cb_khoahoc.addItem("")
        self.cb_khoahoc.addItem("")
        self.cb_khoahoc.addItem("")
        self.cb_khoahoc.addItem("")
        self.cb_khoahoc.addItem("")
        self.cb_khoahoc.addItem("")
        self.btnThem = QtWidgets.QPushButton(parent=Dialog)
        self.btnThem.setGeometry(QtCore.QRect(30, 140, 80, 30))
        self.btnThem.setObjectName("btnThem")
        self.btnLoad = QtWidgets.QPushButton(parent=Dialog)
        self.btnLoad.setGeometry(QtCore.QRect(140, 140, 80, 30))
        self.btnLoad.setObjectName("btnLoad")
        self.btnSua = QtWidgets.QPushButton(parent=Dialog)
        
        self.btnSua = QtWidgets.QPushButton(parent=Dialog)
        self.btnSua.setGeometry(QtCore.QRect(260, 140, 80, 30))
        self.btnSua.setText("Sửa")
        self.btnSua.setObjectName("btnSua") 

        self.btnXoa = QtWidgets.QPushButton(parent=Dialog)
        self.btnXoa.setGeometry(QtCore.QRect(360, 140, 80, 30))
        self.btnXoa.setText("Xóa")
        self.btnXoa.setObjectName("btnXoa")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 190, 460, 180))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Đăng ký khóa học"))
        self.label.setText(_translate("Dialog", "Tên học viên"))
        self.label_2.setText(_translate("Dialog", "Email"))
        self.label_3.setText(_translate("Dialog", "Khóa học"))
        self.cb_khoahoc.setItemText(0, _translate("Dialog", "Python"))
        self.cb_khoahoc.setItemText(1, _translate("Dialog", "Java"))
        self.cb_khoahoc.setItemText(2, _translate("Dialog", "Web"))
        self.cb_khoahoc.setItemText(3, _translate("Dialog", "PHP"))
        self.cb_khoahoc.setItemText(4, _translate("Dialog", "C#"))
        self.cb_khoahoc.setItemText(5, _translate("Dialog", "C"))
        self.btnThem.setText(_translate("Dialog", "Đăng ký"))
        self.btnLoad.setText(_translate("Dialog", "Xem danh sách"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Tên"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Khóa học"))



def connect_db():
    return sqlite3.connect("course.db")

def create_table():
    conn = connect_db()
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS dangky ( id INTEGER PRIMARY KEY AUTOINCREMENT, ten TEXT, email TEXT UNIQUE, khoa TEXT)""")
    conn.commit()
    conn.close()


class MainApp(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

        create_table()

        self.ui.btnThem.clicked.connect(self.dangky)
        self.ui.btnLoad.clicked.connect(self.load_data)
        self.ui.btnSua.clicked.connect(self.sua)
        self.ui.btnXoa.clicked.connect(self.xoa)
        self.ui.tableWidget.cellClicked.connect(self.fill_data)

    def load_data(self):
        conn = connect_db()
        cur = conn.cursor()
        cur.execute("SELECT ten, email, khoa FROM dangky")
        data = cur.fetchall()
        conn.close()

        self.ui.tableWidget.setRowCount(0)

        for i, row in enumerate(data):
            self.ui.tableWidget.insertRow(i)
            for j, val in enumerate(row):
                self.ui.tableWidget.setItem(i, j, QTableWidgetItem(str(val)))

    def dangky(self):
        ten = self.ui.txt_ten.text().strip()
        email = self.ui.txt_email.text().strip()
        khoa = self.ui.cb_khoahoc.currentText()

        if not ten or not email:
            QMessageBox.warning(self, "Lỗi", "Nhập thiếu dữ liệu")
            return

        conn = None
        try:
            conn = connect_db()
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO dangky (ten, email, khoa) VALUES (?, ?, ?)",
                (ten, email, khoa)
            )
            conn.commit()

            QMessageBox.information(self, "OK", "Đăng ký thành công")
            self.clear_form()

        except sqlite3.IntegrityError:
            QMessageBox.warning(self, "Lỗi", "Email đã tồn tại")

        finally:
            if conn:
                conn.close()


    def sua(self):
        ten = self.ui.txt_ten.text().strip()
        email = self.ui.txt_email.text().strip()
        khoa = self.ui.cb_khoahoc.currentText()

        if not email:
            QMessageBox.warning(self, "Lỗi", "Chọn dữ liệu cần sửa")
            return

        conn = connect_db()
        cur = conn.cursor()

        cur.execute(""" UPDATE dangky SET ten=?, khoa=? WHERE email=? """, (ten, khoa, email))

        conn.commit()
        conn.close()

        QMessageBox.information(self, "OK", "Đã sửa")
        self.load_data()
        self.clear_form()
    
    def xoa(self):
        row = self.ui.tableWidget.currentRow()

        if row == -1:
            QMessageBox.warning(self, "Lỗi", "Chọn dòng cần xóa")
            return

        email = self.ui.tableWidget.item(row, 1).text()

        conn = connect_db()
        cur = conn.cursor()
        cur.execute("DELETE FROM dangky WHERE email=?", (email,))
        conn.commit()
        conn.close()

        QMessageBox.information(self, "OK", "Đã xóa")
        self.load_data()
        self.clear_form()
    def fill_data(self, row, col):
        self.ui.txt_ten.setText(self.ui.tableWidget.item(row, 0).text())
        self.ui.txt_email.setText(self.ui.tableWidget.item(row, 1).text())
        self.ui.cb_khoahoc.setCurrentText(self.ui.tableWidget.item(row, 2).text())

    def clear_form(self):
        self.ui.txt_ten.clear()
        self.ui.txt_email.clear()
        self.ui.cb_khoahoc.setCurrentIndex(0)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    window = MainApp()  
    window.show()
    sys.exit(app.exec())

