# Form implementation generated from reading ui file 'nhansu.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        self.txt_cccd = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_cccd.setGeometry(QtCore.QRect(20, 20, 150, 25))
        self.txt_cccd.setObjectName("txt_cccd")
        self.txt_ten = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_ten.setGeometry(QtCore.QRect(200, 20, 150, 25))
        self.txt_ten.setObjectName("txt_ten")
        self.txt_ns = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_ns.setGeometry(QtCore.QRect(380, 20, 150, 25))
        self.txt_ns.setObjectName("txt_ns")
        self.cb_gt = QtWidgets.QComboBox(parent=Dialog)
        self.cb_gt.setGeometry(QtCore.QRect(20, 60, 150, 25))
        self.cb_gt.setObjectName("cb_gt")
        self.cb_gt.addItem("")
        self.cb_gt.addItem("")
        self.txt_dc = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_dc.setGeometry(QtCore.QRect(200, 60, 330, 25))
        self.txt_dc.setObjectName("txt_dc")
        self.btnThem = QtWidgets.QPushButton(parent=Dialog)
        self.btnThem.setGeometry(QtCore.QRect(20, 100, 80, 30))
        self.btnThem.setObjectName("btnThem")
        self.btnSua = QtWidgets.QPushButton(parent=Dialog)
        self.btnSua.setGeometry(QtCore.QRect(120, 100, 80, 30))
        self.btnSua.setObjectName("btnSua")
        self.btnXoa = QtWidgets.QPushButton(parent=Dialog)
        self.btnXoa.setGeometry(QtCore.QRect(220, 100, 80, 30))
        self.btnXoa.setObjectName("btnXoa")
        self.txt_tim = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_tim.setGeometry(QtCore.QRect(320, 100, 150, 30))
        self.txt_tim.setObjectName("txt_tim")
        self.btnTim = QtWidgets.QPushButton(parent=Dialog)
        self.btnTim.setGeometry(QtCore.QRect(480, 100, 80, 30))
        self.btnTim.setObjectName("btnTim")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 150, 540, 220))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Quản lý nhân sự"))
        self.txt_cccd.setPlaceholderText(_translate("Dialog", "CCCD"))
        self.txt_ten.setPlaceholderText(_translate("Dialog", "Họ tên"))
        self.txt_ns.setPlaceholderText(_translate("Dialog", "Ngày sinh"))
        self.cb_gt.setItemText(0, _translate("Dialog", "Nam"))
        self.cb_gt.setItemText(1, _translate("Dialog", "Nữ"))
        self.txt_dc.setPlaceholderText(_translate("Dialog", "Địa chỉ"))
        self.btnThem.setText(_translate("Dialog", "Thêm"))
        self.btnSua.setText(_translate("Dialog", "Sửa"))
        self.btnXoa.setText(_translate("Dialog", "Xóa"))
        self.txt_tim.setPlaceholderText(_translate("Dialog", "Tìm kiếm..."))
        self.btnTim.setText(_translate("Dialog", "Tìm"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "CCCD"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Họ tên"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Ngày sinh"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Giới tính"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Địa chỉ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
